# Generated by Django 4.2 on 2024-08-11 17:37

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'permissions': [('custom_view_newsletter', 'Может просматривать любой новостной бюллетень'), ('view_users', 'Может просматривать список пользователей сервиса'), ('block_users', 'Может заблокировать пользователей сервиса'), ('disable_newsletter', 'Может отключить новостные бюллетени')],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
